[book]
title = "The Miden protocol"
authors = ["Miden team"]
description = "Description and core structures for the Miden Rollup protocol"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-base"
mathjax-support = true

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
warning-policy = "ignore"
