import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Autogenerate entire sidebar tree from /docs
 * This will include:
 * - Static docs from this aggregator repo
 * - All vendor repos' docs synced into subfolders
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
